baseURL: "https://mapfumo.github.io/"
languageCode: en-us
title: Antony Mapfumo
pagination:
  pagerSize: 3
theme: PaperMod
ShowReadingTime: false
params:
  assets:
    favicon: "/img/favicon.png"
  social: true
  disableThemeToggle: false
  defaultTheme: dark
  homeInfoParams:
    Title: "Welcome / Mauya / Siyalemukela"
    Content: Welcome to my tech blog, where I explore practical engineering topics across **data communications, embedded systems, IIoT, distributed technologies, and energy-aware system design**. I focus on clear, grounded insights drawn from real experiments, open-source work, and ongoing research in high-performance connected devices.

  socialIcons:
    - name: twitter
      url: "https://twitter.com/mapfumo"
    - name: github
      url: "https://github.com/mapfumo"
    - name: email
      url: "mailto:mapfumo@icloud.com"
  cover:
    linkFullImages: true
  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 5
    - identifier: portfolio
      name: Portfolio
      url: /portfolio/
      weight: 10
    - identifier: tutorials
      name: Tutorials
      url: /tutorials/
      weight: 12
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 15
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 20
    - identifier: about
      name: About
      url: /about/
      weight: 25
